### ISSUE TITLE
Exception when starting DGTCentaurMods.

### ISSUE THREAD

**Issue by wormstein** [EdNekebno/DGTCentaurMods#119]
Exception when starting DGTCentaurMods.

```
Traceback (most recent call last):
  File "/home/pi/dev/DGTCentaur/DGTCentaurMods/game/menu.py", line 182, in <module>
    result = doMenu(menu)
  File "/home/pi/dev/DGTCentaur/DGTCentaurMods/game/menu.py", line 125, in doMenu
    res = board.getBoardState()
  File "/home/pi/dev/DGTCentaur/DGTCentaurMods/board/board.py", line 668, in getBoardState
    tval = (resp[x] * 256) + resp[x+1]
IndexError: index out of range
```

Is not happening all the time. Looks like it depends on serial response. Restarting the service usually fixes it.
Probably we need a len() there...

**Comment by EdNekebno** [comment]
That's normally when the hardware controller doesn't respond. Usually that's because another process is using it (like the centaur process, as you say probably because other process has locked the serial). Better to trace it back to where the serial port is opened and catch the failure there.

**Comment by wormstein** [comment]
True. In this case DGTCentaurMods.service was running.
