### ISSUE TITLE
Moves in centaur mode are not saved in the database

### ISSUE THREAD

**Issue by chemtech1** [EdNekebno/DGTCentaurMods#127]
In version 1.01 the moves in centaur mode are not saved. All moves played against an engine like ct800 are saved. can anyone confirm this?

**Comment by wormstein** [comment]
I corrected some wrong parhs in SF source but I don't see it working.
I am not so good ar C++, I let someone else to have an eye. My changes are here: https://github.com/wormstein/Stockfish/tree/db-bug

**Comment by EdNekebno** [comment]
In principle those paths look good. It might be that the code to detect the process isn't working in the later raspbian. I'll look when I can get a new sdcard to test on.

**Comment by wormstein** [comment]
Likely this is something in SF code as playing stockfish through gamemanager works fine.

```
[Event "2850 ELO"]
[Site ""]
[Date "2022-03-05 11:16:53"]
[Round ""]
[White "Player"]
[Black "Stockfish UCI"]
[Result ""]
[Source "stockfish"]

1. h4 d5
2. ```

**Comment by EdNekebno** [comment]
Yes - I think that's right.
Just thought I can try and compile your latest SF onto my board and swap it in and see what happens. No need to wait for me to get an SDcard then. Will try in a bit

**Comment by wormstein** [comment]
Confirmed fixed. Thanks Ed.
Merging into [wormstein/Stockfish/master](https://github.com/wormstein/Stockfish/tree/master).
