### ISSUE TITLE
Hand and Brain not working

### ISSUE THREAD

**Issue by chemtech1** [EdNekebno/DGTCentaurMods#129]
Thanks for the update very cool. I found two things:
1.
The HandandBrain menu does not open. There is an error in the menu.py. In line 493, the following line must be inserted:

enginemenu = {'stockfish': 'Stockfish'}

2.
HandandBrain against the Stockfish engine doesn't work. It works with the other engines.
or or if stockfish doesn't work, then:
enginemenu = {}

**Comment by EdNekebno** [comment]
Thanks for this. Because stockfish is the "brain" and stockfish isn't so great at setting levels, playing stockfish against stockfish would mostly be a losing game for most people - so it was the intent that it play against a different engine. I used the second one, it works great.
