### ISSUE TITLE
With the back button you can not get out of the resigndraw menu

### ISSUE THREAD

**Issue by chemtech1** [EdNekebno/DGTCentaurMods#135]
If the question mark button is pressed in the game, the resigndrawmenu appears. If you now press the back button, the menu is no longer displayed. However, you are still in the menu. If you now press the top or bottom arrow key, the function in the menu will still be executed.
Solution: 
If the line „inmenu=0“ is inserted after line 96 in the file gamemanager.py, you can get out of the menu by pressing the back key.

**Comment by wormstein** [comment]
Confirmed bug. There is a strange behaviour happening when pressing BACK while in the resign/draw menu.
I can exit the menu but board stops responding to key presses for some reason. Investigating.

**Comment by wormstein** [comment]
This is fixed in next update. Keeping it open until release.
