### ISSUE TITLE
Board evaluation does not work with every engine

### ISSUE THREAD

**Issue by chemtech1** [EdNekebno/DGTCentaurMods#140]
Hello,
The board evaluation does not work with every engine. For example, the chess engine arasam returns this string during the analysis:
{'string': 'book moves: (Nf3 95, Nc3 5), choosing Nf3'}
This leads to an error in the evaluationGraphs function.
Maybe it's a good idea to always use the same chess engine here that is known to work, such as the stockfish engine.

**Comment by EdNekebno** [comment]
Thanks, that's a shame. I think you're right then - we have to use stockfish for the analysis.
