### ISSUE TITLE
Pawn promotion error in eboard.py in Version 1.2.0

### ISSUE THREAD

**Issue by chemtech1** [EdNekebno/DGTCentaurMods#147]
I played some games with the Chess Dojo app and the Chess for Android app. I noticed that the pawn promotion does not work. The promotion menu is not displayed and the game does not continue. I looked at the eboard.py code and found a few semicolon errors.  In line 577, 611, 868, 1162. After removing the semicolons, the error is unfortunately still there. The error occurs at the moment when the promotion menu should be displayed. 
If line 588 "epaper.promotionOptions(9)" is removed, the code continues to run and it is possible to perform a pawn promotion. But then an error occurs.  I can't get any further at this point. Maybe this helps to find the error.

**Comment by wormstein** [comment]
Hi @[chemtech1](https://github.com/chemtech1),
it does help us to track down where it comes from. But we need a bit more information here:
1. Is this happening when play an engine too or just when emulating an eboard? 
2. When you say 'the game does not continue', can you come back to main menu or you need to hard rebioot the board?

Thanks,,

**Comment by chemtech1** [comment]
Hi @wormstein 
It happens when I simulate an eboard. It works when playing against an engine.
To your second question. When I put the pawn on the 8th row, the square on the 7th row flashes and nothing happens. The promotion menu is not displayed. Communication with the app continues. When I continue playing in the app, squares on the DGT board also light up. But you can't continue playing with the board. If the Bluetooth connection is interrupted, the DGT Centaur returns to the start menu.

**Comment by wormstein** [comment]
FYI, this is not ignored :) I am attempting a fix...

**Comment by wormstein** [comment]
I put this here. The console output when g8 is triggered. Looks like it gets inside the display function in epaper.py, then something breaks.
```
DOWN: g8
switching off leds
White turn
1
0
sending clock
8d000a00000000000009
DGT_RETURN_SERIALNR
DGT_RETURN_LONG_SERIALNR
Disaply promotion function started
drawing promotion options
An impossible exception really did just occur! Don't ask me how!
```

**Comment by wormstein** [comment]
Confirmed fix. Nice one Ed!
