### ISSUE TITLE
Clock doesn't show correct time above 60 minutes

### ISSUE THREAD

**Issue by zeedo** [EdNekebno/DGTCentaurMods#153]
If you play a game that is over 60 minutes the clock is incorrect. This is because of the formatting where it shows the minutes only and not the hours. Makes you think you're in a 30 minute game when you're in a 90 minute game.

I have looked at the code for this and will fix it. Just logging the issues so we know it's there.

**Comment by EdNekebno** [comment]
Closing as I think zeedo already did an accepted pull request for this some time ago.
