### ISSUE TITLE
Board doesn't show promoting options when playing on lichess

### ISSUE THREAD

**Issue by joaomrcarvalho** [EdNekebno/DGTCentaurMods#156]
Sample from log (printing some extra variables):

message1 =  {'type': 'gameState', 'moves': 'g1f3 e7e6 h2h4 f8c5 c2c3 h7h6 d2d4 c5d6 e2e3 b8c6 g2g3 g8f6 f1b5 a7a6 b5c6 d7c6 e1g1 e8g8 b1a3 f6d5 e3e4 d5f6 f1e1 d6a3 b2a3 e6e5 f3e5 d8e7 a1b1 f8d8 b1b3 c6c5 d4d5 e7e5 c1f4 e5e7 h4h5 c8d7 e4e5 d7a4 e5f6 e7f6 f4c7 a4b3 d1b3 d8c8 d5d6 g7g5 b3b6 f6c3 e1e6 f7e6 d6d7 c8f8 a3a4 c3d2', 'wtime': datetime.datetime(1970, 1, 1, 0, 23, 5, 950000, tzinfo=datetime.timezone.utc), 'btime': datetime.datetime(1970, 1, 1, 0, 25, 56, 40000, tzinfo=datetime.timezone.utc), 'winc': datetime.datetime(1970, 1, 1, 0, 0, 20, tzinfo=datetime.timezone.utc), 'binc': datetime.datetime(1970, 1, 1, 0, 0, 20, tzinfo=datetime.timezone.utc), 'status': 'started'}
messagehelp =  wtime': datetime.datetime(1970, 1, 1, 0, 23, 5, 950000, tzinfo=datetime.timezone.utc), 'btime': datetime.datetime(1970, 1, 1, 0, 25, 56, 40000, tzinfo=datetime.timezone.utc), 'winc': datetime.datetime(1970, 1, 1, 0, 0, 20, tzinfo=datetime.timezone.utc), 'binc': datetime.datetime(1970, 1, 1, 0, 0, 20, tzinfo=datetime.timezone.utc), 'status': 'started'}
messagehelp =  btime': datetime.datetime(1970, 1, 1, 0, 25, 56, 40000, tzinfo=datetime.timezone.utc), 'winc': datetime.datetime(1970, 1, 1, 0, 0, 20, tzinfo=datetime.timezone.utc), 'binc': datetime.datetime(1970, 1, 1, 0, 0, 20, tzinfo=datetime.timezone.utc), 'status': 'started'}
switching off leds
make move called
white player name is set
drawing promotion options
switching off leds
make move called
white player name is set
making move

**Comment by EdNekebno** [comment]
This didn't reproduce. It's most likely connected to display timing issues which should be improved in 1.3.0. I'll close for now and we can re-open if it persists.
