### ISSUE TITLE
No such file or directory: '/dev/ttyS0'

### ISSUE THREAD

**Issue by pkkid** [EdNekebno/DGTCentaurMods#158]
After soldering on a USB port to the original pizero (not the pizero2w), I used the Powershell **SD card self setup tool** to get my pi up and running. For the most part things were working great out of the box. However, EdNekebno, who had a manual setup, and Me, who used the automated setup, were hitting the following exception. The commonality between us is we were both using the original pizero that came with the DGT board. I suspect this is a difference between the pi hardware versions, but I could be wrong. Upon applying the patch further below, the exception was resolved and DGTMods were able to successfully start. (albeit, I have no working screen yet which we think is a different issue).

Exception was found in /var/log/daemon.log

```python
Dec  2 10:17:52 dgtcentaur systemd[1]: Starting DGTCentaurMods software....
Dec  2 10:17:56 dgtcentaur systemd[1]: Started DGTCentaurMods software..
Dec  2 10:17:58 dgtcentaur python3[977]: Traceback (most recent call last):
Dec  2 10:17:58 dgtcentaur python3[977]:   File "/usr/local/lib/python3.9/dist-packages/serial/serialposix.py", line 322, in open
Dec  2 10:17:58 dgtcentaur python3[977]:     self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
Dec  2 10:17:58 dgtcentaur python3[977]: FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyS0'
Dec  2 10:17:58 dgtcentaur python3[977]: During handling of the above exception, another exception occurred:
Dec  2 10:17:58 dgtcentaur python3[977]: Traceback (most recent call last):
Dec  2 10:17:58 dgtcentaur python3[977]:   File "/opt/DGTCentaurMods/board/board.py", line 54, in <module>
Dec  2 10:17:58 dgtcentaur python3[977]:     ser = serial.Serial("/dev/ttyS0", baudrate=1000000, timeout=0.2)
Dec  2 10:17:58 dgtcentaur python3[977]:   File "/usr/local/lib/python3.9/dist-packages/serial/serialutil.py", line 244, in __init__
Dec  2 10:17:58 dgtcentaur python3[977]:     self.open()
Dec  2 10:17:58 dgtcentaur python3[977]:   File "/usr/local/lib/python3.9/dist-packages/serial/serialposix.py", line 325, in open
Dec  2 10:17:58 dgtcentaur python3[977]:     raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
Dec  2 10:17:58 dgtcentaur python3[977]: serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyS0: [Errno 2] No such file or directory: '/dev/ttyS0'
Dec  2 10:17:58 dgtcentaur python3[977]: During handling of the above exception, another exception occurred:
Dec  2 10:17:58 dgtcentaur python3[977]: Traceback (most recent call last):
Dec  2 10:17:58 dgtcentaur python3[977]:   File "/opt/DGTCentaurMods/game/menu.py", line 22, in <module>
Dec  2 10:17:58 dgtcentaur python3[977]:     from DGTCentaurMods.board import *
Dec  2 10:17:58 dgtcentaur python3[977]:   File "/opt/DGTCentaurMods/board/board.py", line 57, in <module>
Dec  2 10:17:58 dgtcentaur python3[977]:     ser.close()
Dec  2 10:17:58 dgtcentaur python3[977]: NameError: name 'ser' is not defined
Dec  2 10:17:58 dgtcentaur systemd[1]: DGTCentaurMods.service: Main process exited, code=exited, status=1/FAILURE
Dec  2 10:17:58 dgtcentaur systemd[1]: DGTCentaurMods.service: Failed with result 'exit-code'.
Dec  2 10:17:58 dgtcentaur systemd[1]: DGTCentaurMods.service: Consumed 2.312s CPU time.
```

The patch we applied and is documented in the [Deploy the Mods on the original hardware](https://github.com/bpycinski/DGTCentaurMods/wiki/Deploy-the-Mods-on-the-original-hardware) tutorial is the following. Note: I did not use his full tutorial in my setup, I used the **SD card self setup tool** and only applied this patch after seeing the above exception.
```bash
# The Pi Zero default UART device is `ttyAMA0`, not `ttyS0`, we need to
# fix this /dev/serial0 links to the available device
sed -i -e 's@/dev/ttyS0@/dev/serial0@' /opt/DGTCentaurMods/board/board.py
```

There are two things to note here:
1. I suspect a simple check for the existence of `/dev/ttyS0` and falling back to `/dev/serial0` would make things work OK without needing to patch anything, but there could be some deeper issue hiding here.
2. The exception handler around creating the `ser` object is also failing because ser is not defined yet.

**Comment by pkkid** [comment]
From Discord:
> You wouldn't have the issue on the 2w because the code was written to point to `/dev/ttyS0` which exists. On the pizero, its `/dev/ttyAMA0`. However, the thinking is `/dev/serial0` is a symlink we should be using that always points to the right thing. Can someone with a 2w confirm that there is in fact a symlink for ` /dev/serial0 -> /dev/ttyS0`?

Also, this may be fixed in PR #157 - Thats a huge PR, so we should get a fix regardless of the state of that PR.

**Comment by pkkid** [comment]
Can someone with a pizero2w please ssh in and confirm that there is a symlink `/dev/serial0` pointing to `/dev/ttyS0`

**Comment by joaomrcarvalho** [comment]
> Can someone with a pizero2w please ssh in and confirm that there is a symlink `/dev/serial0` pointing to `/dev/ttyS0`?

Confirmed on a Pi Zero 2W :)

**Comment by pkkid** [comment]
Sweet, so I think the fix is really simple, just change `/dev/ttyS0` in build.py to `/dev/serial0`.

**Comment by joaomrcarvalho** [comment]
Should be fixed on https://github.com/EdNekebno/DGTCentaurMods/pull/159

**Comment by EdNekebno** [comment]
Closing this issue, I believe this is fixed in the pull request I accepted the other day as board.py now uses /dev/serial0
