### ISSUE TITLE
Startup stays in endless loop until "Quit orig Centaur" from webinterface

### ISSUE THREAD

**Issue by kF13Ld** [EdNekebno/DGTCentaurMods#188]
Hello everyone,

I have version 1.3.2 installed on my Raspberry Pi Zero W. When I start the board via ">||", the light on the board keeps moving forever. After a while, I can open the webinterface http://ip/configure and there click on "Quit orig Centaur". Then it takes a short while until the DGT display shows the Centaur MODS "Press v to start". After that, everything seems to work fine.

So my device seems to be in some sort of boot loop. What can I do to not always have to use a browser to use the chess board?

I can SSH to the device (once the webinterface loads as well) but don't know what to look for.

Regards
kF13Ld

**Comment by EdNekebno** [comment]
That suggests the service isn't starting as it restarts it when you click Quit orig Centaur. How did you install and did you use raspbian 32 bit legacy?

**Comment by kF13Ld** [comment]
I installed it a couple of months ago, but never really used it. Instead used the original Pi Zero with original firmware. Now wanted to try it again.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

```
$ uname -a
Linux dgtcentaur 6.1.21+ #1642 Mon Apr  3 17:19:14 BST 2023 armv6l GNU/Linux

```

--> armv6l is the 32 bit version.

I might have used apt update && apt dist-upgrade before...

What is the name of the service that needs to start? Can I not just do something like
`systemctl enable <name.service>`

Regards
 kF13Ld

**Comment by wormstein** [comment]
Hi,
the service is enabled by default, no need to enable it in systemd. But the service (DGTCentaurMods.service) will not start if there is a hardware issue, like bad soldering.

A.

**Comment by kF13Ld** [comment]
Ok, now that I know the name:
```
# systemctl status DGTCentaurMods.service
● DGTCentaurMods.service - DGTCentaurMods software.
     Loaded: loaded (/etc/systemd/system/DGTCentaurMods.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2023-11-24 21:56:52 CET; 42s ago
    Process: 339 ExecStartPre=/bin/sleep 4 (code=exited, status=0/SUCCESS)
    Process: 387 ExecStart=python3 game/menu.py (code=exited, status=1/FAILURE)
   Main PID: 387 (code=exited, status=1/FAILURE)
        CPU: 2.074s

Nov 24 21:56:39 dgtcentaur systemd[1]: Starting DGTCentaurMods software....
Nov 24 21:56:44 dgtcentaur systemd[1]: Started DGTCentaurMods software..
Nov 24 21:56:52 dgtcentaur systemd[1]: DGTCentaurMods.service: Main process exited, code=exited, status=1/FAILURE
Nov 24 21:56:52 dgtcentaur systemd[1]: DGTCentaurMods.service: Failed with result 'exit-code'.
Nov 24 21:56:52 dgtcentaur systemd[1]: DGTCentaurMods.service: Consumed 2.074s CPU time.

```

When I start it manually, it works:
```
# systemctl status DGTCentaurMods
● DGTCentaurMods.service - DGTCentaurMods software.
     Loaded: loaded (/etc/systemd/system/DGTCentaurMods.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-11-24 22:13:27 CET; 6s ago
    Process: 830 ExecStartPre=/bin/sleep 4 (code=exited, status=0/SUCCESS)
   Main PID: 831 (python3)
      Tasks: 1 (limit: 414)
        CPU: 1.982s
     CGroup: /system.slice/DGTCentaurMods.service
             └─831 python3 game/menu.py

Nov 24 22:13:23 dgtcentaur systemd[1]: Starting DGTCentaurMods software....
Nov 24 22:13:27 dgtcentaur systemd[1]: Started DGTCentaurMods software..

```

The big question is: why does it fail for the first (automatic) start? Can it really be bad soldering, if it works at the second try?

**Comment by wormstein** [comment]
try checking journalctl for the exact error?
`journalctl -xu DGTCentaurMods`

**Comment by EdNekebno** [comment]
Hmmmm....a zero w. It's been a while since we've tried it with anything but a 2w I think, maybe there is a timing issue with other stuff starting up. Try changing the /bin/sleep 4 to longer.

**Comment by kF13Ld** [comment]
Thank you, that helped!

I changed the /bin/sleep from 4 to 6 seconds:

```
$ cat /etc/systemd/system/DGTCentaurMods.service 
[Unit]
Description=DGTCentaurMods software.
After=network.target

[Service]
Environment=PYTHONUNBUFFERED=1
ExecStartPre=/bin/sleep 6
ExecStart=python3 game/menu.py
WorkingDirectory=/opt/DGTCentaurMods
Environment="PYTHONPATH=/opt"
StandardOutput=file:/var/log/modmenuoutput.log
StandardError=file:/var/log/modmenuoutput.log
Restart=no
User=pi

[Install]
WantedBy=multi-user.target

```

Then a 
`# systemctl daemon-reload`

Now, it boots just fine!
